
###
GET http://localhost:3000/messages


###
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "hi there new thing after implementing Di"
}

###
GET http://localhost:3000/messages/951